### ISSUE TITLE
"Pugixml - Set Value" not working

### ISSUE THREAD

**Issue by GeekThis** [FF-Plugins-Active/FF_PugiXml#1]
The blueprint node "Pugixml - Set Value" is not working and return false every time.

Unreal Engine version : 5.4.4

**Comment by ffreality** [comment]
It is 02:04 AM in our country. So, I can look at it at tomorrow.
(I wore my pyjamas)

but try to put breaklines to one of this function's falses.
https://github.com/FF-Plugins-Active/FF_PugiXml/blob/main/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1330

and write here where you get your false exactly.
But it will be good if I add some log string outputs.

**Comment by GeekThis** [comment]
Yeah don't worry. Same for me

After a few tries, it's in this line that the false return occurs : 
https://github.com/FF-Plugins-Active/FF_PugiXml/blob/041163efb32ead2d9a1aa88f56a601730975bfec/Source/FF_PugiXml/ThirdParty/pugixml/pugixml.cpp#L5856

However, if I add this condition "type_ != node_element" to the if statement : 
https://github.com/FF-Plugins-Active/FF_PugiXml/blob/041163efb32ead2d9a1aa88f56a601730975bfec/Source/FF_PugiXml/ThirdParty/pugixml/pugixml.cpp#L5855
It returns true, but instead of replacing the old value with the new value, it appends the new value to the old value.

**Comment by ffreality** [comment]
> Yeah don't worry. Same for me
> 
> After a few tries, it's in this line that the false return occurs :
> 
> https://github.com/FF-Plugins-Active/FF_PugiXml/blob/041163efb32ead2d9a1aa88f56a601730975bfec/Source/FF_PugiXml/ThirdParty/pugixml/pugixml.cpp#L5856
> 
> However, if I add this condition "type_ != node_element" to the if statement :
> 
> https://github.com/FF-Plugins-Active/FF_PugiXml/blob/041163efb32ead2d9a1aa88f56a601730975bfec/Source/FF_PugiXml/ThirdParty/pugixml/pugixml.cpp#L5855
> 
> 
> It returns true, but instead of replacing the old value with the new value, it appends the new value to the old value.

Okay, first of all I really appreciate to point this bug.
I solved the problem but I would like to explain it.

That value which we want to modify is not actually a direct property of node element but it is a `pcdata child node`. Also as you pointed, `pugixml's set_value()` doesn't accept `node_element` type.

So, i created another UOBJECT type (inherited it from `UFFPugiXml_Node` and add another member variable for `value_node`.
Because we have to store that node. If we don't do that, we can't reach it to modify it when we add another child to that `node_element`.

You don't need to modify your blueprints too much. (but I suggest you to check neverthless because if you defined a variable, you need to change it). At C++ level, PugiXml_Set_Value just checks if it is element type or not, and get actual value target.

Btw. I updated pugixml version to master.

https://github.com/FF-Plugins-Active/FF_PugiXml/commit/d00f6281c2cfc4d7fe68241c766b79195105fc69

**Comment by GeekThis** [comment]
The `Set_Value()` node doesn't work when the `Target_Node` reference comes from the  `Find_Child_By_Name()` node. Howerver, it works when the  `Target_Node` reference comes from the  `Add_Node_Element()` node.


After some testings, I realized that, when using a `Find_Child_By_Name()` node,  `Node_Type==node_element` is true but `IsValid(Temp_Element)` is false in this line:
https://github.com/FF-Plugins-Active/FF_PugiXml/blob/d00f6281c2cfc4d7fe68241c766b79195105fc69/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1346


Also, even though my knwoledge of C++ and XML is limited, I find this if statement a bit odd:
https://github.com/FF-Plugins-Active/FF_PugiXml/blob/d00f6281c2cfc4d7fe68241c766b79195105fc69/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1351

**Comment by ffreality** [comment]
> The `Set_Value()` node doesn't work when the `Target_Node` reference comes from the `Find_Child_By_Name()` node. Howerver, it works when the `Target_Node` reference comes from the `Add_Node_Element()` node.
> 
> After some testings, I realized that, when using a `Find_Child_By_Name()` node, `Node_Type==node_element` is true but `IsValid(Temp_Element)` is false in this line:
> 
> https://github.com/FF-Plugins-Active/FF_PugiXml/blob/d00f6281c2cfc4d7fe68241c766b79195105fc69/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1346
> 
> Also, even though my knwoledge of C++ and XML is limited, I find this if statement a bit odd:
> 
> https://github.com/FF-Plugins-Active/FF_PugiXml/blob/d00f6281c2cfc4d7fe68241c766b79195105fc69/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1351

Yes you are right about the issue.
Find_Child_By_Name node should return `_Element` UOBJECT. I will look at it and other getters in the morning.

**Comment by ffreality** [comment]
> The `Set_Value()` node doesn't work when the `Target_Node` reference comes from the `Find_Child_By_Name()` node. Howerver, it works when the `Target_Node` reference comes from the `Add_Node_Element()` node.
> 
> After some testings, I realized that, when using a `Find_Child_By_Name()` node, `Node_Type==node_element` is true but `IsValid(Temp_Element)` is false in this line:
> 
> https://github.com/FF-Plugins-Active/FF_PugiXml/blob/d00f6281c2cfc4d7fe68241c766b79195105fc69/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1346
> 
> Also, even though my knwoledge of C++ and XML is limited, I find this if statement a bit odd:
> 
> https://github.com/FF-Plugins-Active/FF_PugiXml/blob/d00f6281c2cfc4d7fe68241c766b79195105fc69/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1351

For the "oddness" of the code,
problem is not about XML's itself. It is about PugiXML's implementation.
As I mention before, node element's value is actually a `pcdata` child node.

First `if` checks that target node is element node or not. If it is element, it will run set_value() node on its child value (value node)

we use second `if` because some XML node types don't contain value directly.
So, if we have a correct node type, `set_value()` run directly on themselves.

and finally if target node is not the correct one, function return false.

I know that I don't need to check them but if PugiXml maintainers decide to throw exceptions for wrong node types, your project will crash (unless try and catch). I don't want this. Error management should be graceful. I false return, some branches and UI hints is enough.

We have two types UOBJECT because we need to access pcdata value node regardless of that child's name or index to change value. So, we need special object for node element.

I am open suggestions about alternatives 😁

**Comment by GeekThis** [comment]
What I meant by "odd", is that this statement will be false every time because we are checking if the same value is equal to different values at the same time. Shouldn't be `||` instead of `&&`? Or am I missing something?

**Comment by ffreality** [comment]
> What I meant by "odd", is that this statement will be false every time because we are checking if the same value is equal to different values at the same time. Shouldn't be `||` instead of `&&`? Or am I missing something?

yes yes it's my bad 😁

I changed code.

- I deleted seperated and inherited `UOBJECT` type for `node_element`.
- I changed && to ||

Because,
1. After some research I found out that `XML node element` shouldn't contain multiple `pcdata` node.
PugiXML allows that but it looks like two values merged (just like your `set_value()` test). So, I added a restriction. If the target node element already has a value (`or we can say pcdata`), you can't add another one. This also allow us to find value node in the future without storing it. So, we don't need new `UOBJECT`.

2. All my getter functions (find by name and etc.) `creates new UOBJECT` after finding wanted node. So, if I try to store value node, I can't find it neverthless if we don't have a solution like first option. `Add_Node_Element` was an exception because we created `value/pcdata node`. So, we could just pointed it in `node element UOBJECT`

3. If target node element doesn't have `pcdata` node, `our Set Value function` will add it.

I will add JSON based error log system. Because if you have lots of plugins, you need lots of infos in your log.
